"use client";
import { Activity, Database, FileSearch, GitBranch, ListChecks, PlayCircle, ShieldCheck } from "lucide-react";
import { PresentState } from "@/app/lib/runState";

const items = [["overview", "Overview", Activity], ["issues", "Issues", ListChecks], ["lineage", "Lineage", GitBranch], ["data", "Data", Database], ["actions", "Actions", ShieldCheck], ["details", "Run details", FileSearch]] as const;
export function AppShell({ active, onNavigate, state, children, apiOnline, llmAvailable, llmProvider, agentExecution }: { active: string; onNavigate: (id: string) => void; state: PresentState; children: React.ReactNode; apiOnline: boolean; llmAvailable: boolean | null; llmProvider: string | null; agentExecution?: { mode: string; llm_used: boolean; fallback_used: boolean } }) {
  const label = state.replaceAll("_", " ");
  const agentLabel = agentExecution?.llm_used ? "LLM AGENT" : "AGENT FALLBACK";
  return <div className="min-h-screen bg-[#FFF4EB] text-[#3D1534]"><header className="h-14 border-b border-[#3D1534] bg-[#3D1534] px-4 lg:px-6 flex items-center justify-between text-[#FFF4EB]"><div className="flex items-center gap-3"><div className="grid h-7 w-7 place-items-center rounded bg-[#3E4B8E] font-black text-white">O</div><span className="text-sm font-bold tracking-[.16em]">OBSIDIAN DQ</span></div><div className="flex items-center gap-3 text-xs"><span className={`hidden sm:inline-flex items-center gap-1.5 ${apiOnline ? "text-emerald-300" : "text-rose-300"}`}><i className="h-1.5 w-1.5 rounded-full bg-current" /> API {apiOnline ? "CONNECTED" : "OFFLINE"}</span><span className={`hidden md:inline ${agentExecution?.llm_used ? "text-emerald-300" : "text-amber-300"}`}>{agentLabel}</span><span className="hidden lg:inline text-[#A6BCC9]">LLM {llmProvider ? `${llmProvider} configured` : "not configured"}</span><span className={`rounded border px-2 py-1 font-semibold ${state === "REVIEW_REQUIRED" ? "border-amber-300 bg-amber-100 text-amber-900" : state === "BLOCKED" ? "border-rose-300 bg-rose-100 text-rose-800" : "border-emerald-300 bg-emerald-100 text-emerald-800"}`}>{label}</span></div></header><div className="flex"><aside className="sticky top-0 hidden h-[calc(100vh-3.5rem)] w-56 shrink-0 border-r border-[#A6BCC9] bg-white p-3 lg:block"><div className="mb-3 px-3 text-[10px] font-bold tracking-widest text-[#3E4B8E]">CURRENT RUN</div>{items.map(([id, label, Icon]) => <button key={id} onClick={() => onNavigate(id)} className={`mb-1 flex w-full items-center gap-3 rounded-md px-3 py-2.5 text-left text-sm transition ${active === id ? "bg-[#3E4B8E] text-[#FFF4EB]" : "text-[#3D1534] hover:bg-[#F6E0B6]"}`}><Icon size={16}/>{label}</button>)}<div className="mt-8 border-t border-[#A6BCC9] pt-4 px-3 text-xs leading-relaxed text-[#3D1534]/70">Agent proposals control the action; tools, guardrails, and approval keep execution safe.</div></aside><main className="min-w-0 flex-1 p-4 md:p-7">{children}</main></div></div>;
}
